name: translate
description: Alternative front-end for Google Translate, serving as a Free and Open Source translator with over a hundred languages available.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  arna:
    git: https://github.com/MahanRahmati/Arna.git
  flutter_riverpod: ^2.0.0-dev.9
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
